name: github pages
on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v5
        with:
          version: 8
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - run: pnpm run docs

      # - name: Copy static files to docs
      # - name: Ensure target directory exists
      #   run: mkdir -p docs/media/style

      - name: Copy JS to docs
        run: cp public/demo.js docs/media/demo.js

      - name: Copy CSS to docs
        run: cp public/demo.css docs/media/demo.css

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./docs
          token: ${{ secrets.PAGE_GITHUB_TOKEN }}
